-- ============================================================================
-- TRADETAX DATABASE SETUP - FULL
-- Run this in Supabase Dashboard → SQL Editor
-- ============================================================================

-- Step 1: Create TRANSACTIONS table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    category TEXT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    description TEXT,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Step 2: Create MILEAGE_TRIPS table
CREATE TABLE IF NOT EXISTS mileage_trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    purpose TEXT,
    "from" TEXT,
    "to" TEXT,
    miles DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Step 3: Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_mileage_trips_user_id ON mileage_trips(user_id);

-- Step 4: Enable Row Level Security (RLS)
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE mileage_trips ENABLE ROW LEVEL SECURITY;

-- Step 5: Create policies for user data isolation
-- Each user can only see/edit their own data
DROP POLICY IF EXISTS "Users can CRUD own transactions" ON transactions;
DROP POLICY IF EXISTS "Users can CRUD own mileage" ON mileage_trips;

CREATE POLICY "Users can CRUD own transactions" ON transactions
    FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can CRUD own mileage" ON mileage_trips
    FOR ALL USING (auth.uid() = user_id);

-- Step 6: Create a function to auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name)
    VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger for new user signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================================================
-- Verify setup:
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';
-- Should show: transactions, mileage_trips, profiles
-- ============================================================================

SELECT 'Database setup complete! Tables created: transactions, mileage_trips, profiles' as status;
